//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionElectronicaDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancaria
    {
        public int id_cuentaBancaria { get; set; }
        public string codigo_moneda { get; set; }
        public int id_tipo { get; set; }
        public string nombre_banco { get; set; }
        public string nombre_titular { get; set; }
        public string numero_cuenta { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual TipoCuentaBancaria TipoCuentaBancaria { get; set; }
    }
}
