//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionElectronicaDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturacionElectronica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturacionElectronica()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int num_factura { get; set; }
        public string numero_ruc { get; set; }
        public string codigo_documentoElectronico { get; set; }
        public string numero_serie { get; set; }
        public string numero_correlativo { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<int> codigo_operacion { get; set; }
        public string codigo_moneda { get; set; }
        public Nullable<decimal> tipo_cambio { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<decimal> exonerada { get; set; }
        public Nullable<decimal> inafecta { get; set; }
        public Nullable<decimal> gravada { get; set; }
        public Nullable<decimal> igv { get; set; }
        public Nullable<decimal> gratuita { get; set; }
        public Nullable<decimal> total_boleta { get; set; }
        public string observacion { get; set; }
        public string codigo_TipoCredito { get; set; }
        public string codigo_TipoDebito { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual Tipo_Operacion Tipo_Operacion { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Tipo_DocumentoElectronico Tipo_DocumentoElectronico { get; set; }
        public virtual Tipo_NotaCredito Tipo_NotaCredito { get; set; }
        public virtual Tipo_NotaDebito Tipo_NotaDebito { get; set; }
    }
}
